### ISSUE TITLE
RoMote not recognizing this plugin is installed

### ISSUE THREAD

**Issue by e-t-l** [wseemann/RoMote-PrivateListening#3]
Not sure whether to put this as an issue for this app or the main RoMote app, but I wanted to try private listening to so downloaded and installed this plugin as directed by the RoMote in-app prompt, but RoMote is not recognizing the plugin. When I try to press Private Listening, it stoll prompts me to install this plugin. I've tried closing the app and clearing the cache. Both apps are up to date.

**Comment by joshl129** [comment]
+1. I would really appreciate this feature but also understand the plug-in can be discontinued at any time

**Comment by wseemann** [comment]
@e-t-l Thanks so much for reporting this issue! This should be fixed in RoMote version 1.0.21. Android 11 added some new restrictions on package visibility that was preventing the plugin from being detected. Please let me know if you encounter any issues after the fix.
