### ISSUE TITLE
Ear Buds

### ISSUE THREAD

**Issue by TonyaCbolt** [wseemann/RoMote-PrivateListening#6]

**Comment by sh433** [comment]
Hello

**Comment by whateverths** [comment]
why just why this is pretty much useless without earbuds

**Comment by wseemann** [comment]
What is the point of commenting on this issue? You created an account just to slam someone else's work? Does that make you feel better about yourself? You don't have the slightest idea what it took to write this application. If you don't like my app then don't use it. This community is better off without people like you who contribute nothing while trying to tear down someone elses work.

**Comment by sh433** [comment]
Excuse me

**Comment by sh433** [comment]
Loook I am sorry if I made u feel some way but I was just trying to make my
air buds connect to the tv
